amcl:
  ros__parameters:
    alpha1: 0.2 #0.01
    alpha2: 0.2 
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: base_footprint
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: true #false
    global_frame_id: map
    lambda_short: 0.1
    laser_likelihood_max_dist: 3.0
    laser_max_range: 5.0 #100.0
    laser_min_range: -1.0
    laser_model_type: likelihood_field
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: odom
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: nav2_amcl::DifferentialMotionModel
    save_pose_rate: 0.5
    scan_topic: scan
    set_initial_pose: true
    sigma_hit: 0.1
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.1
    update_min_d: 0.1
    use_sim_time: false
    z_hit: 0.9
    z_rand: 0.5
    z_short: 0.05
bt_navigator:
  ros__parameters:
    bt_loop_duration: 10
    default_nav_through_poses_bt_xml: navigate_through_poses_w_replanning_and_recovery.xml
    default_nav_to_pose_bt_xml: navigate_to_pose_w_replanning_and_recovery.xml
    default_server_timeout: 20
    enable_groot_monitoring: true
    global_frame: map
    groot_zmq_publisher_port: 1666
    groot_zmq_server_port: 1667
    odom_topic: /odom
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_compute_path_through_poses_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_truncate_path_action_bt_node
    - nav2_goal_updater_node_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_distance_traveled_condition_bt_node
    - nav2_single_trigger_bt_node
    - nav2_is_battery_low_condition_bt_node
    - nav2_navigate_through_poses_action_bt_node
    - nav2_navigate_to_pose_action_bt_node
    - nav2_remove_passed_goals_action_bt_node
    - nav2_planner_selector_bt_node
    - nav2_controller_selector_bt_node
    - nav2_goal_checker_selector_bt_node
    - nav2_path_longer_on_approach_bt_node
    - nav2_controller_cancel_bt_node
    robot_base_frame: base_link
    use_sim_time: false
controller_server:
  ros__parameters:
    FollowPath:
      plugin: nav2_rotation_shim_controller::RotationShimController
      primary_controller: dwb_core::DWBLocalPlanner
      # Rotation Shim
      angular_dist_threshold: 0.4
      forward_sampling_distance: 0.5
      rotate_to_heading_angular_vel: 1.8
      max_angular_accel: 6.0
      simulate_ahead_time: 5.0
      # DWB
      debug_trajectory_details: true
      min_vel_x: 0.0
      min_vel_y: 0.0
      max_vel_x: 1.0 #0.6
      max_vel_y: 0.0
      max_vel_theta: 0.6 #1.0
      min_speed_xy: 0.0
      max_speed_xy: 0.6
      min_speed_theta: 0.0
      acc_lim_x: 3.0 #2.5
      acc_lim_y: 0.0
      acc_lim_theta: 3.2
      decel_lim_x: -3.0 #-2.5
      decel_lim_y: 0.0
      decel_lim_theta: -3.2
      vx_samples: 10 #20
      vy_samples: 5
      vtheta_samples: 20
      sim_time: 1.0 #4.0
      linear_granularity: 0.05
      angular_granularity: 0.025
      transform_tolerance: 0.2
      xy_goal_tolerance: 0.2
      trans_stopped_velocity: 0.7
      short_circuit_trajectory_evaluation: true
      stateful: true
      critics:
      - BaseObstacle
      - RotateToGoal
      - Oscillation
      - GoalAlign
      - PathAlign
      - PathDist
      - GoalDist
      # - ObstacleFootprint
      ObstacleFootprint.scale: 16.0   #32.0
      BaseObstacle.scale: 0.9   #0.2
      GoalAlign.forward_point_distance: 0.1
      GoalAlign.scale: 1.0 #24.0
      GoalDist.scale: 0.8 #24.0
      PathAlign.forward_point_distance: 0.2 #0.1
      PathAlign.scale: 1.0 #32   # 작은값, 경로 정렬에 덜 집중 | 큰값, 경로 정렬에 더 집중
      PathDist.scale: 1.0 #32.0  # 작은값, 장애물 회피에 더 집중 | 큰값, 최단거리에 더 집중
      RotateToGoal.lookahead_time: -1.0
      RotateToGoal.scale: 32.0
      RotateToGoal.slowing_factor: 5.0
    PurePursuit:
      allow_reversing: false
      angular_dist_threshold: 0.785
      desired_linear_vel: 0.8999999761581421
      forward_sampling_distance: 0.5
      lookahead_dist: 0.6
      lookahead_time: 1.5
      max_allowed_time_to_collision_up_to_carrot: 1.0
      max_angular_accel: 3.2
      max_lookahead_dist: 1.5
      max_robot_pose_search_dist: 10.0
      min_approach_linear_velocity: 0.05
      min_lookahead_dist: 0.3
      plugin: nav2_rotation_shim_controller::RotationShimController
      primary_controller: nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController
      regulated_linear_scaling_min_radius: 10.0 #0.9
      regulated_linear_scaling_min_speed: 0.25
      rotate_to_heading_angular_vel: 1.0
      rotate_to_heading_min_angle: 0.785
      simulate_ahead_time: 5.0
      transform_tolerance: 0.3
      use_cost_regulated_linear_velocity_scaling: false
      use_interpolation: false
      use_regulated_linear_velocity_scaling: true
      use_rotate_to_heading: true
      use_velocity_scaled_lookahead_dist: false
    controller_frequency: 10.0
    controller_plugins:
    - FollowPath
    - PurePursuit
    failure_tolerance: 0.3
    general_goal_checker:
      plugin: nav2_controller::SimpleGoalChecker
      stateful: true
      xy_goal_tolerance: 0.3 #0.25
      yaw_goal_tolerance: 0.2
    goal_checker_plugins:
    - general_goal_checker
    min_theta_velocity_threshold: 0.001
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    progress_checker:
      movement_time_allowance: 10.0
      plugin: nav2_controller::SimpleProgressChecker
      required_movement_radius: 0.5
    progress_checker_plugin: progress_checker
    use_sim_time: false
controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: false
global_costmap:
  global_costmap:
    ros__parameters:
      always_send_full_costmap: True
      footprint: '[[0.15, 0.10], [-0.15, 0.10], [-0.15, -0.10], [0.15, -0.10]]'
      footprint_padding: 0.02
      global_frame: map
      denoise_layer:                                        # 추가됨
        plugin: "nav2_costmap_2d::DenoiseLayer"
        enabled: True
        minimal_group_size: 8
        group_connectivity_type: 8
      inflation_layer:
        cost_scaling_factor: 10.0
        inflation_radius: 0.2
        neutral_cost: 2
        plugin: nav2_costmap_2d::InflationLayer
      obstacle_layer:
        enabled: true
        observation_sources: scan pointcloud
        plugin: nav2_costmap_2d::ObstacleLayer
        scan:
          clearing: true
          data_type: LaserScan
          marking: true
          max_obstacle_height: 2.0
          obstacle_max_range: 3.0  # 3.0
          obstacle_min_range: 0.0
          raytrace_max_range: 20.0 #20.0
          raytrace_min_range: 0.0
          topic: /scan_v2
        pointcloud:
          clearing: true
          data_type: PointCloud2
          marking: true
          max_obstacle_height: 2.0
          obstacle_max_range: 3.0  # 3.0
          obstacle_min_range: 0.0
          raytrace_max_range: 20.0
          raytrace_min_range: 0.0
          topic: /obstacle_points
      plugins:
      - static_layer
      - obstacle_layer
      - inflation_layer
      - denoise_layer
      publish_frequency: 2.0
      resolution: 0.01
      robot_base_frame: base_link
      static_layer:
        map_subscribe_transient_local: true
        plugin: nav2_costmap_2d::StaticLayer
      track_unknown_space: true
      update_frequency: 2.0
      use_sim_time: false
local_costmap:
  local_costmap:
    ros__parameters:
      always_send_full_costmap: true
      footprint: '[[0.15, 0.10], [-0.15, 0.10], [-0.15, -0.10], [0.15, -0.10]]'
      footprint_padding: 0.01 #0.05
      global_frame: map
      height: 3
      denoise_layer:                                        # 추가됨
        plugin: "nav2_costmap_2d::DenoiseLayer"
        enabled: True
        minimal_group_size: 8
        group_connectivity_type: 8                     # 여기까지
      inflation_layer:
        cost_scaling_factor: 10.0
        inflation_radius: 0.35
        neutral_cost: 2
        plugin: nav2_costmap_2d::InflationLayer
      obstacle_layer:
        enabled: true
        observation_sources: scan pointcloud
        plugin: nav2_costmap_2d::ObstacleLayer
        scan:
          clearing: true
          data_type: LaserScan
          marking: true
          max_obstacle_height: 2.0
          obstacle_max_range: 3.0  # 3.0
          obstacle_min_range: 0.0
          raytrace_max_range: 20.0
          raytrace_min_range: 0.0
          topic: /scan_v2
        pointcloud:
          clearing: true
          data_type: PointCloud2
          marking: true
          max_obstacle_height: 2.0
          obstacle_max_range: 3.0  # 3.0
          obstacle_min_range: 0.0
          raytrace_max_range: 20.0
          raytrace_min_range: 0.0
          topic: /obstacle_points
      plugins:
      - obstacle_layer
      - inflation_layer
      - denoise_layer                                         # 추가됨
      publish_frequency: 2.0
      resolution: 0.01
      robot_base_frame: base_link
      rolling_window: true
      update_frequency: 5.0
      use_sim_time: false
      width: 5
map_saver:
  ros__parameters:
    free_thresh_default: 0.25
    map_subscribe_transient_local: true
    occupied_thresh_default: 0.65
    save_map_timeout: 5.0
    use_sim_time: false
map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: ''
planner_server:
  ros__parameters:
    GridBased:
      allow_unknown: true
      plugin: nav2_navfn_planner/NavfnPlanner
      tolerance: 0.5
      use_astar: true
    expected_planner_frequency: 20.0
    planner_plugins:
    - GridBased
    use_sim_time: false
robot_state_publisher:
  ros__parameters:
    use_sim_time: false
velocity_smoother:
  ros__parameters:
    deadband_velocity:
    - 0.0
    - 0.0
    - 0.0
    feedback: OPEN_LOOP
    max_accel:
    - 2.5
    - 0.0
    - 3.2
    max_decel:
    - -2.5
    - 0.0
    - -3.2
    max_velocity:
    - 0.26
    - 0.0
    - 1.0
    min_velocity:
    - -0.26
    - 0.0
    - -1.0
    odom_duration: 0.1
    odom_topic: odom
    scale_velocities: false
    smoothing_frequency: 20.0
    use_sim_time: false
    velocity_timeout: 1.0
waypoint_follower:
  ros__parameters:
    loop_rate: 2000
    stop_on_failure: false
    use_sim_time: false
    wait_at_waypoint:
      enabled: true
      plugin: nav2_waypoint_follower::WaitAtWaypoint
      waypoint_pause_duration: 200
    waypoint_task_executor_plugin: wait_at_waypoint
